### PR TITLE
Big cpp split

### PR DESCRIPTION
**Pull request by cgcostume**
alphabetically grouped function and binding sources, and added precompiled headers for msvc:  ```/bigobj``` is not required anymore for msvc.

some rough build times (sorry for various configs, but ```OPTION_EXTENSIVE_META=On```):

| system | compiler | branch | config | time |
| --- | --- | --- | --- | --- |
| i5-3337U (laptop) | msvc2015 | master | release lib | 7 min 10 sec |
| i5-3337U (laptop) | msvc2015 | big_cpp_split | release lib, w/o pre-compiled | 3 min 30 sec |
| i5-3337U (laptop) | msvc2015 | big_cpp_split | release lib | 3 min 00 sec |
| i7-4790 (jenkins) | msvc2015 | master | generate, debug & release all | 4 min 10 sec |
| i7-4790 (jenkins) | msvc2015 | big_cpp_split | generate, debug & release all | 2 min 19 sec |
| i7-4790 (jenkins) | clang3.5 | master | debug & release all | 3 min 15 sec |
| i7-4790 (jenkins) | clang3.5 | big_cpp_split | debug & release all | 4 min 04 sec |
| i7-4790 (jenkins) | clang3.5 | big_cpp_split | debug & release all ```-j8``` | 2 min 04 sec |
| i7-4790 (jenkins) | gcc4.9 | master | debug & release all | 2 min 40 sec |
| i7-4790 (jenkins) | gcc4.9 | big_cpp_split | debug & release all | 4 min 20 sec |
| i7-4790 (jenkins) | gcc4.9 | big_cpp_split | debug & release all ```-j8``` | 1 min 05 sec |

I would like to discuss further use of precompiled header for gcc as well as for msvc on ```functions_*.cpp``` (```functions.h```) or perhaps discard use of pre-compiled header at all ...

Remark: in the ```<gl/functions.h>``` preprocessor groups were added to allow partial include in cpp files (for internal use only) without affecting the api (except for the source of course) - please review, both preprocessor groups and precompiled headers are probably not worth the marginal impact on compile time?

### CODE REVIEW

**Comment by cgcostume** [comment]
Jenkins, retest this please.

**Comment by scheibel** [comment]
Seems like precompiled headers add more complexity to our build system. We should check if precompiled headers have a compile-time impact on dependend projects (e.g., globjects, gloperate, ...).

**Comment by cgcostume** [comment]
The pre-compiled headers are currently only for internal, specific sources - not for the project. So should have no impact there. Anyway, we probably should go without pre-compiled headers at all.

**Comment by cgcostume** [comment]
* For msvc: precompiled header are exclusively used for alphabetically grouped sources (non public / non-API source area)
* For non-msvc: no grouped sources and no pre-compiled headers are used at all

gcc and clang build times are as before (master) and msvc is now on gcc level and requires no ```/bigobj```- going to merge when checks are valid

**Comment by cgcostume** [comment]
Jenkins, retest this please.

**Comment by cgcostume** [comment]
Jenkins, retest this please.

**Comment by cgcostume** [comment]
Jenkins, retest this please.

**Comment by cgcostume** [comment]
manually tested ...

**Pull request merged**
